### ISSUE TITLE
AzureML pipeline package update

### ISSUE THREAD

**Issue by Giusmon94** [microsoft/Templates-For-Dynamics-365-Supply-Chain-Management-Demand-Forecasting-With-Azure-Machine-Learning#7]
Hi all,

Yesterday (12/04/2023) azureml-pipeline package for python has been updated. Running the forecast through the pipeline, the package will be updated and the pipeline won't work anymore giving the error below.

I fixed the error specifying the package version to install (1.49.0). Has someone find a different solution?

Thanks,
Giuseppe

## Logs

<details>
<summary>run.py logs</summary>

```

Traceback (most recent call last):
  File "run.py", line 20, in <module>
    from azureml.pipeline.steps import ParallelRunConfig, ParallelRunStep
  File "/azureml-envs/azureml_f3f7e6c5fb83d94df23933000bf02da3/lib/python3.8/site-packages/azureml/pipeline/steps/__init__.py", line 26, in <module>
    from .automl_step import AutoMLStep, AutoMLStepRun
  File "/azureml-envs/azureml_f3f7e6c5fb83d94df23933000bf02da3/lib/python3.8/site-packages/azureml/pipeline/steps/automl_step.py", line 26, in <module>
    from azureml.train.automl import constants
  File "/azureml-envs/azureml_f3f7e6c5fb83d94df23933000bf02da3/lib/python3.8/site-packages/azureml/train/automl/__init__.py", line 26, in <module>
    from azureml.train.automl.automlconfig import AutoMLConfig
  File "/azureml-envs/azureml_f3f7e6c5fb83d94df23933000bf02da3/lib/python3.8/site-packages/azureml/train/automl/automlconfig.py", line 17, in <module>
    from azureml._common._error_definition.user_error import \
ImportError: cannot import name 'ArgsNotSupportedForScenario' from 'azureml._common._error_definition.user_error' (/azureml-envs/azureml_f3f7e6c5fb83d94df23933000bf02da3/lib/python3.8/site-packages/azureml/_common/_error_definition/user_error.py)

```
</details>

**Comment by andreygarmash** [comment]
hi, we're working on making it compatible with the latest version.
